# Generated by Django 5.0.4 on 2024-05-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
