# Generated by Django 5.0.4 on 2024-05-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AddField(
            model_name='customuser',
            name='classroom',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classroom'),
        ),
    ]
