# Generated by Django 5.0.4 on 2024-05-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_subject_teacher_grade_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classroom'),
        ),
    ]
