# Generated by Django 5.0.4 on 2024-05-17 10:12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customuser_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classroom',
            field=models.ForeignKey(blank=True, limit_choices_to=core.models.limit_to_students, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classroom'),
        ),
    ]
