# Generated by Django 5.0.4 on 2024-05-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customuser_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='classroom',
        ),
    ]
