# Generated by Django 5.0.4 on 2024-05-17 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_customuser_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('student', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
