# Generated by Django 5.0.4 on 2024-05-17 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studentinclassroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, related_name='classes_enseignées', to=settings.AUTH_USER_MODEL),
        ),
    ]
