# Generated by Django 5.0.4 on 2024-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_classroom_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='trimester',
            field=models.IntegerField(null=True),
        ),
    ]
