# Generated by Django 5.0.4 on 2024-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_grade_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='note_module',
            field=models.IntegerField(null=True),
        ),
    ]
