# Generated by Django 5.0.4 on 2024-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_grade_school_year_alter_grade_note_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
