# Generated by Django 5.0.4 on 2024-05-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.classroom'),
        ),
    ]
