# Generated by Django 5.0.4 on 2024-05-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_subject_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
    ]
