# Generated by Django 5.0.4 on 2024-05-18 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_classroom_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'teacher'}, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
