# Generated by Django 5.0.4 on 2024-05-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_subject_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='note_module',
            new_name='grade',
        ),
    ]
