# Generated by Django 5.0.4 on 2024-05-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_note_module_grade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='trimester',
        ),
    ]
