# Generated by Django 5.0.4 on 2024-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_grade_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='trimester',
            field=models.IntegerField(null=True),
        ),
    ]
