# Generated by Django 5.0.4 on 2024-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_subject_trimester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='trimester',
        ),
        migrations.AddField(
            model_name='grade',
            name='trimester',
            field=models.IntegerField(null=True),
        ),
    ]
