# Generated by Django 5.0.4 on 2024-05-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_subject_trimester_grade_trimester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
    ]
