# Generated by Django 5.0.4 on 2024-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_subject_teachers_subject_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='school_year',
        ),
        migrations.AddField(
            model_name='classroom',
            name='school_year',
            field=models.IntegerField(null=True),
        ),
    ]
