# Generated by Django 5.0.4 on 2024-05-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_grade_school_year_classroom_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='school_year',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
