# Generated by Django 5.0.4 on 2024-05-18 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_subject_teachers_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinclassroom',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignment', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
