# Generated by Django 5.0.4 on 2024-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_studentinclassroom_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='core.subject'),
        ),
    ]
