# Generated by Django 5.0.4 on 2024-05-18 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_subject_classroom_classroom_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinclassroom',
            name='student',
        ),
        migrations.AddField(
            model_name='studentinclassroom',
            name='student',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'student'}, related_name='classroom_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
