# Generated by Django 5.0.4 on 2024-05-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_studentinclassroom_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=10, null=True),
        ),
    ]
