# Generated by Django 5.0.4 on 2024-05-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_absence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absence',
            new_name='Absences',
        ),
    ]
