# Generated by Django 5.0.4 on 2024-05-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_anouncements_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anouncements',
            new_name='Announcements',
        ),
    ]
