# Generated by Django 5.0.4 on 2024-05-24 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rename_anouncements_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendars',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.classroom'),
        ),
    ]
