# Generated by Django 5.0.4 on 2024-05-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_calendars_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='calendar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.calendars'),
        ),
    ]
