# Generated by Django 5.0.4 on 2024-05-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_calendars_teacher_customuser_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.calendars'),
        ),
    ]
