# Generated by Django 5.0.4 on 2024-05-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_customuser_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='calendar',
        ),
    ]
