# Generated by Django 5.0.4 on 2024-05-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_customuser_matricule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher information'},
        ),
    ]
