# Generated by Django 5.0.4 on 2024-05-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_student_classroom_student_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInClassroom',
        ),
    ]
