# Generated by Django 5.0.4 on 2024-05-24 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_subject_teacher_subject_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='subject',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('Continous', 'Continous'), ('Test', 'Test'), ('Exam', 'Exam'), ('Final', 'Final')], default='Continous', max_length=30),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='core.student'),
        ),
        migrations.AlterField(
            model_name='absences',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.student'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classrooms', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='core.student'),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_written', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='calendar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_calendar', to='core.calendars'),
        ),
    ]
