# Generated by Django 5.0.4 on 2024-05-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_announcements_category_alter_student_matricule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
