# Generated by Django 5.0.4 on 2024-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='is_user_only',
            field=models.BooleanField(default=False),
        ),
    ]
