# Generated by Django 5.0.4 on 2024-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_announcements_is_user_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
