# Generated by Django 5.0.4 on 2024-05-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_announcements_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
