# Generated by Django 5.0.4 on 2024-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_announcements_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Recruitment', 'Recruitment')], default='General', max_length=255),
        ),
    ]
