# Generated by Django 5.0.4 on 2024-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_announcements_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Recruitment', 'Recruitment'), ('Events', 'Events'), ('Trips', 'Trips')], default='General', max_length=255),
        ),
    ]
