# Generated by Django 5.0.4 on 2024-05-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_announcements_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
    ]
