# Generated by Django 5.0.4 on 2024-05-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_homework_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homework'},
        ),
    ]
