# Generated by Django 5.0.4 on 2024-05-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_homework_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='HomeworkAssignment',
        ),
    ]
