# Generated by Django 5.0.4 on 2024-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_rename_homework_homeworkassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/'),
        ),
    ]
