# Generated by Django 5.0.4 on 2024-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_homeworksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkassignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks_assignments/'),
        ),
    ]
