# Generated by Django 5.0.4 on 2024-05-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_teacher_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.classroom'),
        ),
    ]
