# Generated by Django 5.0.4 on 2024-05-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_homeworksubmission_response'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('homework', 'student')},
        ),
    ]
