# Generated by Django 5.0.4 on 2024-05-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_homeworksubmission_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absences',
            name='subject',
        ),
    ]
