# Generated by Django 5.0.4 on 2024-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_remove_absences_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='absences',
            name='trimester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1),
        ),
    ]
