# Generated by Django 5.0.4 on 2024-05-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_remove_absences_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absences',
            name='is_justified',
            field=models.BooleanField(default=False),
        ),
    ]
