# Generated by Django 5.0.4 on 2024-05-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_absences_is_justified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absences',
            name='number_of_absences',
        ),
        migrations.RemoveField(
            model_name='absences',
            name='number_of_justitifed_absences',
        ),
        migrations.RemoveField(
            model_name='absences',
            name='number_of_unjustitifed_absences',
        ),
    ]
