# Generated by Django 5.0.4 on 2024-05-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_remove_absences_number_of_absences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absences',
            name='justification',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Medical', 'Medical'), ('Other', 'Other')], default='Parent', max_length=30),
        ),
    ]
