# Generated by Django 5.0.4 on 2024-05-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_absences_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absences',
            name='justification',
            field=models.CharField(blank='True', choices=[('Parent', 'Parent'), ('Medical', 'Medical'), ('Other', 'Other')], default='Parent', max_length=30),
        ),
    ]
