# Generated by Django 5.0.4 on 2024-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_absences_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('Continous', 'Continous'), ('Test', 'Test'), ('Exam', 'Exam')], default='Continous', max_length=30),
        ),
    ]
