# Generated by Django 5.0.4 on 2024-05-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_remove_calendars_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='core.calendars'),
        ),
    ]
