# Generated by Django 5.0.4 on 2024-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_classroom_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='calendars',
            name='end',
        ),
        migrations.RemoveField(
            model_name='calendars',
            name='start',
        ),
        migrations.AddField(
            model_name='calendars',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendars',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
