# Generated by Django 5.0.4 on 2024-05-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendars',
            name='timeslots',
            field=models.ManyToManyField(to='core.timeslot'),
        ),
    ]
