# Generated by Django 5.0.4 on 2024-05-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_calendars_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='description',
        ),
    ]
