# Generated by Django 5.0.4 on 2024-05-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_classroom_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='core.calendars'),
        ),
    ]
