# Generated by Django 5.0.4 on 2024-05-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_timeslot_content_alter_timeslot_time_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='calendars',
            name='week_start',
        ),
    ]
