# Generated by Django 5.0.4 on 2024-05-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_remove_calendars_week_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendars',
            name='calendar_type',
            field=models.CharField(choices=[('CLASS', 'Classroom Schedule'), ('CAFE', 'Cafeteria Menu'), ('EVENT', 'Events')], default='CLASS', max_length=5),
        ),
    ]
