# Generated by Django 5.0.4 on 2024-05-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_timeslot_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendars',
            options={'verbose_name_plural': 'Calendars'},
        ),
    ]
