# Generated by Django 5.0.4 on 2024-05-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_alter_timeslot_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendars',
            name='end_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendars',
            name='start_week',
            field=models.DateField(blank=True, null=True),
        ),
    ]
