# Generated by Django 5.0.4 on 2024-05-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_calendars_end_week_calendars_start_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='core.calendars'),
        ),
    ]
