# Generated by Django 5.0.4 on 2024-05-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_alter_timeslot_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='core.calendars'),
        ),
    ]
