# Generated by Django 5.0.4 on 2024-05-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_classroom_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='calendar',
        ),
    ]
