# Generated by Django 5.0.4 on 2024-05-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_remove_teacher_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='end',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='start',
        ),
    ]
