# Generated by Django 5.0.4 on 2024-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_alter_classroom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_additional',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('P1', 'Preparatory 1'), ('P2', 'Preparatory 2'), ('E1', 'Elementary 1'), ('E2', 'Elementary 2'), ('E3', 'Elementary 3'), ('E4', 'Elementary 4'), ('E5', 'Elementary 5'), ('M1', 'Middle 1'), ('M2', 'Middle 2'), ('M3', 'Middle 3'), ('M4', 'Middle 4'), ('H1', 'High 1'), ('H2', 'High 2'), ('H3', 'High 3')], default='E1', max_length=2),
        ),
    ]
