# Generated by Django 5.0.4 on 2024-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_courses_file_alter_courses_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='file',
            field=models.FileField(default='courses/403.png', upload_to='courses/'),
        ),
    ]
