# Generated by Django 5.0.4 on 2024-05-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_alter_courses_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='file',
            field=models.FileField(upload_to='courses/'),
        ),
    ]
