# Generated by Django 5.0.4 on 2024-05-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_courses_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
