# Generated by Django 5.0.4 on 2024-05-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_alter_courses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='level',
            field=models.CharField(choices=[('P1', 'Preparatory 1 / السنة التحضيرية الأولى'), ('P2', 'Preparatory 2 / السنة التحضيرية الثانية'), ('E1', 'Elementary 1 / السنة الأولى ابتدائي'), ('E2', 'Elementary 2 / السنة الثانية ابتدائي'), ('E3', 'Elementary 3 / السنة الثالثة ابتدائي'), ('E4', 'Elementary 4 / السنة الرابعة ابتدائي'), ('E5', 'Elementary 5 / السنة الخامسة ابتدائي'), ('M1', 'Middle 1 / السنة الأولى متوسط'), ('M2', 'Middle 2 / السنة الثانية متوسط'), ('M3', 'Middle 3 / السنة الثالثة متوسط'), ('M4', 'Middle 4 / السنة الرابعة متوسط'), ('STEM1', 'STEM 1st Year / جذع مشترك علوم و تكنولوجيا'), ('LP1', 'Literature and Philosophy 1st Year / جذع مشترك آداب وفلسفة'), ('S2', 'Science 2nd Year / السنة الثانية علمي'), ('S3', 'Science 3rd Year / السنة الثالثة علمي'), ('LP2', 'Literature and Philosophy 2nd Year / السنة الثانية آداب وفلسفة'), ('LP3', 'Literature and Philosophy 3rd Year / السنة الثالثة آداب وفلسفة'), ('MTH2', 'Mathematics 2nd Year / السنة الثانية رياضيات'), ('MTH3', 'Mathematics 3rd Year / السنة الثالثة رياضيات'), ('TM2', 'Technical Mathematics 2nd Year / السنة الثانية تقني رياضي'), ('TM3', 'Technical Mathematics 3rd Year / السنة الثالثة تقني رياضي'), ('FL2', 'Foreign Languages 2nd Year / السنة الثانية لغات أجنبية'), ('FL3', 'Foreign Languages 3rd Year / السنة الثالثة لغات أجنبية')], max_length=5),
        ),
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('P1', 'Preparatory 1 / السنة التحضيرية الأولى'), ('P2', 'Preparatory 2 / السنة التحضيرية الثانية'), ('E1', 'Elementary 1 / السنة الأولى ابتدائي'), ('E2', 'Elementary 2 / السنة الثانية ابتدائي'), ('E3', 'Elementary 3 / السنة الثالثة ابتدائي'), ('E4', 'Elementary 4 / السنة الرابعة ابتدائي'), ('E5', 'Elementary 5 / السنة الخامسة ابتدائي'), ('M1', 'Middle 1 / السنة الأولى متوسط'), ('M2', 'Middle 2 / السنة الثانية متوسط'), ('M3', 'Middle 3 / السنة الثالثة متوسط'), ('M4', 'Middle 4 / السنة الرابعة متوسط'), ('STEM1', 'STEM 1st Year / جذع مشترك علوم و تكنولوجيا'), ('LP1', 'Literature and Philosophy 1st Year / جذع مشترك آداب وفلسفة'), ('S2', 'Science 2nd Year / السنة الثانية علمي'), ('S3', 'Science 3rd Year / السنة الثالثة علمي'), ('LP2', 'Literature and Philosophy 2nd Year / السنة الثانية آداب وفلسفة'), ('LP3', 'Literature and Philosophy 3rd Year / السنة الثالثة آداب وفلسفة'), ('MTH2', 'Mathematics 2nd Year / السنة الثانية رياضيات'), ('MTH3', 'Mathematics 3rd Year / السنة الثالثة رياضيات'), ('TM2', 'Technical Mathematics 2nd Year / السنة الثانية تقني رياضي'), ('TM3', 'Technical Mathematics 3rd Year / السنة الثالثة تقني رياضي'), ('FL2', 'Foreign Languages 2nd Year / السنة الثانية لغات أجنبية'), ('FL3', 'Foreign Languages 3rd Year / السنة الثالثة لغات أجنبية')], default='E1', max_length=5),
        ),
    ]
