# Generated by Django 5.0.4 on 2024-06-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_customuser_date_of_birth_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absences',
            options={'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='remarks',
            options={'verbose_name_plural': 'Remarks'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
