# Generated by Django 5.0.4 on 2024-06-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
