# Generated by Django 5.0.4 on 2024-06-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_parent_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='trimester',
            field=models.IntegerField(choices=[(1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester')], null=True),
        ),
    ]
