# Generated by Django 5.0.4 on 2024-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_alter_grade_trimester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarks',
            name='trimester',
            field=models.IntegerField(choices=[(1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester')], null=True),
        ),
    ]
