# Generated by Django 5.0.4 on 2024-06-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='core.teacher'),
        ),
    ]
