# Generated by Django 5.0.4 on 2024-06-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_alter_grade_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
